graph TD
    subgraph Pantry Shelf
        A[Can] --> B[spec.yaml]
        A --> C[Code]
        C --> I[Mamba Live Env Files...]
        A --> D[Data]
        D --> E[Live Data Dirs...]
        A --> F[Archives]
        F --> J[Mamba Env Archive .tar]
        F --> G[NotebookRepo]
        G --> H[Data Archive .tar Files]
    end