"""Static shell completion script generators for ``ppe``.

Generates bash/zsh/fish completion scripts based on the known ``ppe``
subcommand tree.  These are *static* scripts — no ``argcomplete`` or
other runtime dependency is required; the user sources the printed
script to enable tab-completion.

Usage::

    ppe completions bash      # print bash completion script
    ppe completions zsh       # print zsh completion script
    ppe completions fish      # print fish completion script

Install (bash)::

    eval "$(ppe completions bash)"          # temporary, current shell
    ppe completions bash > /etc/bash_completion.d/ppe  # system-wide

Install (zsh)::

    echo 'eval "$(ppe completions zsh)"' >> ~/.zshrc
    # or, for frameworks using $fpath:
    ppe completions zsh > "${fpath[1]}/_ppe"

Install (fish)::

    ppe completions fish > ~/.config/fish/completions/ppe.fish
"""

from typing import Callable, Optional

# The complete subcommand tree for ``ppe``.
#
# Each entry maps a group command to the list of sub-commands it accepts.
# ``_TOP_LEVEL_ONLY`` lists commands that *do not* take a sub-command.
_PPE_COMMAND_TREE: dict[str, list[str]] = {
    "env": [
        "create",
        "save",
        "restore",
        "ls",
        "info",
        "install",
        "uninstall",
        "relock",
        "rm",
        "ensure",
        "register",
        "unregister",
    ],
    "var": ["add", "rm", "ls"],
    "data": ["ls", "download", "unpack", "pack", "clean"],
    "completions": ["bash", "zsh", "fish"],
}

_TOP_LEVEL_ONLY = ["export", "status", "doctor"]


def _all_groups() -> list[str]:
    """Return all top-level group commands in order."""
    return list(_PPE_COMMAND_TREE.keys()) + _TOP_LEVEL_ONLY


# ---------------------------------------------------------------------------
# bash
# ---------------------------------------------------------------------------


def _gen_bash() -> str:
    """Generate a bash completion script for ``ppe``.

    Uses pure ``COMP_WORDS``/``COMP_CWORD`` parsing so it works even
    without the ``bash-completion`` package installed.
    """
    groups = _all_groups()
    lines = [
        "# bash completion for ppe",
        "# Generated by nb_wrangler.ppe.completions — do not edit by hand.",
        "",
        'if [ -n "$BASH_VERSION" -o -n "$ZSH_VERSION" ]; then',
        "    pep_completion_function() {",
        "        local cur prev words cword",
        '        cur="${COMP_WORDS[COMP_CWORD]}"',
        '        prev="${COMP_WORDS[COMP_CWORD-1]}"',
        "        cword=$COMP_CWORD",
        "",
        '        local top="%s"' % " ".join(groups),
    ]

    # Build per-group command lists
    for group in _PPE_COMMAND_TREE:
        cmds = " ".join(_PPE_COMMAND_TREE[group])
        lines.append('        local %s_cmds="%s"' % (group, cmds))

    lines.append("")
    lines.append("        if [ $cword -eq 1 ]; then")
    lines.append('            COMPREPLY=( $(compgen -W "$top" -- "$cur") )')
    lines.append("            return 0")
    lines.append("        fi")
    lines.append("")
    lines.append("        if [ $cword -eq 2 ]; then")

    for group in _PPE_COMMAND_TREE:
        var = "%s_cmds" % group
        lines.append('            case "$prev" in')
        lines.append(
            '                %s) COMPREPLY=( $(compgen -W "$%s" -- "$cur") ) ;;'
            % (group, var)
        )
        lines.append("            esac")

    lines.append("            return 0")
    lines.append("        fi")
    lines.append("    }")
    lines.append("")
    lines.append("    complete -F pep_completion_function ppe")
    lines.append("fi")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# zsh
# ---------------------------------------------------------------------------


def _gen_zsh() -> str:
    """Generate a zsh completion script for ``ppe``.

    Uses ``_describe`` and ``compadd`` so it works natively in zsh
    without ``bashcompinit``.
    """
    groups = _PPE_COMMAND_TREE
    all_cmds = _all_groups()

    # Build top-level command list with descriptions
    top_lines = []
    for cmd in all_cmds:
        desc = _zsh_desc(cmd)
        top_lines.append(f'    "{cmd}:{desc}"')

    # Build per-group sub-command case branches
    case_lines = []
    for group, subcommands in groups.items():
        case_lines.append(f"        {group})")
        sub_items = " ".join(f"'{s}'" for s in subcommands)
        case_lines.append(f"            compadd -a -- ({sub_items})")
        case_lines.append("            ;;")

    parts = [
        "#compdef ppe",
        "# zsh completion for ppe",
        "# Generated by nb_wrangler.ppe.completions — do not edit by hand.",
        "",
        "_ppe() {",
        "    local state line",
        "",
        "    _arguments -C '1: :->cmd'",
        "",
        "    case $state in",
        "        cmd)",
        "            _describe 'command' commands=(",
        *top_lines,
        "            )",
        "            ;;",
        "    esac",
        "",
        "    if [ $CURRENT -eq 2 ]; then",
        "        case $line[1] in",
        *case_lines,
        "        esac",
        "    fi",
        "}",
        '_ppe "$@"',
        "",
    ]
    return "\n".join(parts)


def _zsh_desc(cmd: str) -> str:
    """Return a short description for a zsh completion entry."""
    if cmd in _FISH_DESCRIPTIONS:
        return _FISH_DESCRIPTIONS[cmd]
    # Sub-command descriptions from completions module
    for group_name, subs in _FISH_SUBCODESCRIPTIONS.items():
        if cmd in subs:
            return subs[cmd]
    return ""


# ---------------------------------------------------------------------------
# fish
# ---------------------------------------------------------------------------


# Short descriptions for each command/group, for a friendlier completion.
_FISH_DESCRIPTIONS: dict[str, str] = {
    "env": "Environment management",
    "var": "Manage environment variables",
    "data": "Manage data archives",
    "export": "Export environment spec",
    "status": "Show system state summary",
    "doctor": "Run self-test checks",
    "completions": "Print shell completion scripts",
}

_FISH_SUBCODESCRIPTIONS: dict[str, dict[str, str]] = {
    "env": {
        "create": "Create a new environment",
        "save": "Pack a live environment into a pantry archive",
        "restore": "Unpack a saved environment and register kernel",
        "ls": "List live envs and pantry shelves",
        "info": "Show detailed info for an environment",
        "install": "Install packages into a live environment",
        "uninstall": "Uninstall packages from a live environment",
        "relock": "Re-curate locks and validate the implicit spec",
        "rm": "Delete environments from live and/or archive",
        "ensure": "Idempotently ensure an env is available",
        "register": "Register Jupyter kernel for an environment",
        "unregister": "Unregister Jupyter kernel for an environment",
    },
    "var": {
        "add": "Add or update env vars",
        "rm": "Remove env vars by glob",
        "ls": "List env vars defined for an environment",
    },
    "data": {
        "ls": "List data archives for an environment",
        "download": "Download data archives",
        "unpack": "Unpack data archives",
        "pack": "Pack live data dirs into archive files",
        "clean": "Delete data archives and/or unpacked files",
    },
    "completions": {
        "bash": "Print bash completion script",
        "zsh": "Print zsh completion script",
        "fish": "Print fish completion script",
    },
}


def _gen_fish() -> str:
    """Generate a fish completion script for ``ppe``."""
    lines: list[str] = [
        "# fish completion for ppe",
        "# Generated by nb_wrangler.ppe.completions — do not edit by hand.",
        "",
    ]

    # Top-level group commands (shown when at subcommand position)
    for group in _all_groups():
        desc = _FISH_DESCRIPTIONS.get(group, "")
        lines.append(
            'complete -c ppe -n "__fish_use_subcommand" -a %s -d "%s"' % (group, desc)
        )

    # Sub-commands for each group (shown after the group is seen)
    for group, subcommands in _PPE_COMMAND_TREE.items():
        sub_descs = _FISH_SUBCODESCRIPTIONS.get(group, {})
        for sub in subcommands:
            desc = sub_descs.get(sub, "")
            lines.append(
                'complete -c ppe -n "__fish_seen_subcommand_from %s" -a %s -d "%s"'
                % (group, sub, desc)
            )

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

_GENERATORS: dict[str, Callable[[], str]] = {
    "bash": _gen_bash,
    "zsh": _gen_zsh,
    "fish": _gen_fish,
}


def generate_completion(shell: str) -> Optional[str]:
    """Return the completion script for *shell*, or ``None`` if unsupported.

    Supported shells: ``bash``, ``zsh``, ``fish``.
    """
    gen = _GENERATORS.get(shell)
    if gen is None:
        return None
    return gen()


def get_supported_shells() -> list[str]:
    """Return the list of supported completion shell names."""
    return list(_GENERATORS.keys())
