name: Trigger NB-Wrangler Curate Workflow

on:
  workflow_dispatch:
    push:
      branches: [dev]
    repository_dispatch:
      types: [notebook_repo_update]

jobs:
  run-wrangler:
    uses: jaytmiller/nb-wrangler/.github/workflows/curate-reusable.yml@dev
    with:
      spec_file: nbw-wrangler-spec.yaml
    secrets: inherit
